apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build-pipelines
  namespace: argocd
spec:
  destination:
    namespace: build-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - my-values.yaml
    path: "."
    repoURL: git@github.com:frenoid/normans-build-pipelines.git
    targetRevision: HEAD
  info:
  - name: "Description: "
    value: "Norman's build pipelines are a collection of Argo Workflows designed for CI/CD"
  syncPolicy:
    automated:
        prune: false
        selfHeal: true
        allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        app: build-pipelines
        owner: normanlim

  ignoreDifferences: []

  # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
  # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
  # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
  # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 10