apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-mcp-server
  namespace: argocd
spec:
  destination:
    namespace: kubernetes-mcp-server
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - my-values.yaml
    path: dify
    repoURL: git@github.com:frenoid/hobby-cluster.git
    targetRevision: HEAD
  info:
  - name: "Description: "
    value: "Model Context Protocol (MCP) server for Kubernetes and OpenShift"
  syncPolicy:
    automated:
        prune: false
        selfHeal: false
        allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        app: kubernetes-mcp-server
        owner: normanlim
        monitoring: enabled

  ignoreDifferences: []

  # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
  # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
  # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
  # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 10
