apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nas-nfs-provisioner
  namespace: argocd
spec:
  destination:
    namespace: nas-nfs-provisioner
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - my-values.yaml
    path: nas-nfs-provisioner
    repoURL: git@github.com:frenoid/hobby-cluster.git
    targetRevision: HEAD
  info:
  - name: "Description: NFS subdir external provisioner is an automatic provisioner that use your existing and already configured NFS server to support dynamic provisioning of Kubernetes Persistent Volumes via Persistent Volume Claims"
    value: ""
  syncPolicy:
    automated:
        prune: false
        selfHeal: true
        allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        app: nas-nfs-provisioner
        owner: normanlim
        monitoring: enabled

  ignoreDifferences: []

  # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
  # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
  # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
  # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 10