kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llmops
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 44089
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /data/kind-cluster/control-plane
    containerPath: /host-path
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
- role: worker
  extraMounts:
  - hostPath: /data/kind-cluster/worker-1
    containerPath: /host-path
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 30080
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 30443
    protocol: TCP
    listenAddress: "0.0.0.0"
- role: worker
  extraMounts:
  - hostPath: /data/kind-cluster/worker-2
    containerPath: /host-path
